<a href="https://colab.research.google.com/github/kuldeep0009-hub/Deep-learning/blob/main/RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [368]:
import tensorflow

In [369]:
from tensorflow.keras.preprocessing.text import one_hot

In [370]:
sent=[
    'i am kuldeep from noida',
    'i am a student',
    'i am from jss college',
    'i lover trading'
]

In [371]:
voc_size=10000

In [372]:
one_hot_apply=[one_hot(words,voc_size)for words in sent]

In [373]:
one_hot_apply

[[3839, 8098, 4353, 4398, 6352],
 [3839, 8098, 9221, 175],
 [3839, 8098, 4398, 4581, 7672],
 [3839, 8830, 2572]]

In [374]:
##so here it means that like we have i am words in my sent they are represented as 8831 as i and 2675 as am
#it means ki jo humara 200 voc_size usme 62th number pr 1 h tb humara vo i h and jb 80th number pr 1 h tb vo humara am h baaki sb zero to ye h humara vector

In [375]:
#word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences

In [376]:
import numpy as np

In [377]:
sent_length=8
embedded_docs=pad_sequences(one_hot_apply,padding='post',maxlen=sent_length) #pre pehle 0 post last me 0 lga dega

In [378]:
print(embedded_docs)

[[3839 8098 4353 4398 6352    0    0    0]
 [3839 8098 9221  175    0    0    0    0]
 [3839 8098 4398 4581 7672    0    0    0]
 [3839 8830 2572    0    0    0    0    0]]


In [379]:
##feature representation
dim=10

In [380]:
model=Sequential()
model.add(Embedding(input_dim=voc_size,output_dim=dim,input_length=sent_length,input_shape=(sent_length,)))
model.compile('adam','mse')



In [381]:
model.summary()

Model: "sequential_25"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_26 (Embedding)        │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [382]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step


array([[[ 0.01346911, -0.01357143,  0.00246454, -0.00398787,
         -0.04073912,  0.04606767,  0.02530434, -0.01821566,
          0.030832  ,  0.04349654],
        [ 0.00219407,  0.01486242, -0.02883944,  0.01856587,
          0.00737245, -0.02583593, -0.00162135,  0.02581841,
         -0.01565685,  0.027317  ],
        [ 0.04427541, -0.04157263, -0.01932426, -0.01165156,
         -0.02262884,  0.01693093,  0.02332026,  0.00282098,
          0.03511504,  0.02696705],
        [-0.0126608 , -0.04395815, -0.01131594, -0.0175925 ,
          0.03491814, -0.04945778, -0.02033095, -0.01858323,
         -0.02555641,  0.00325203],
        [ 0.0423702 , -0.00755554, -0.00169476,  0.02957745,
         -0.01315631,  0.01690097,  0.01877291, -0.04748879,
         -0.01862764, -0.02579916],
        [-0.04038461, -0.01687547, -0.03837084,  0.03953047,
         -0.0308444 , -0.03550069, -0.03292643,  0.0247045 ,
          0.00943668,  0.03975986],
        [-0.04038461, -0.01687547, -0.03837084,  0.0